### ISSUE TITLE
Can't find pxscene-ui redux bindings

### ISSUE THREAD

**Issue by markevans-sky** [Comcast/pxscene-ui#13]
Hi - sorry if this is the wrong channel for this question - wasn't sure where else to post.
In the Readme it says "Optional add-on for integration with Redux" - where is this? I couldn't find it.
Thanks!

**Comment by hhur200** [comment]
hi @markevans-sky , we haven't gotten around to making that repo available here, but it's already been published to npmjs as https://www.npmjs.com/search?q=px2react-redux.

Even though `px2react-redux` expects to find `px2react` (the former name of `pxscene-ui`), you can still use the two together like this:

***package.json:***
```
  ...
  "dependencies": {
    "pxscene-ui": "2.1.3",
    "px2react-redux": "1.0.8",
    "redux": "3.7.2"
  }
  ...
```
***webpack.config.js:***
```
...
resolve: {
    ...
    alias: {
      px2react: 'pxscene-ui'
    }
    ...
  }
...
```

**Comment by markevans-sky** [comment]
great - thanks so much!
I can't seem to access the github.comcast.com link but I can get the package off npm so that's good for now.

**Comment by markevans-sky** [comment]
yup - works a treat - thanks again
